# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 19:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_actividad', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Beneficiarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('cedula', models.IntegerField()),
                ('corregimiento', models.CharField(max_length=200)),
                ('vereda', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_funcionarios', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateField(verbose_name='Fecha de la Visita T\xe9cnica')),
                ('diagnostico', models.TextField()),
                ('recomendaciiones', models.TextField()),
                ('infraestructura', models.TextField()),
                ('hectareas_terreno', models.IntegerField(default=0)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.Actividades')),
                ('beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.Beneficiarios')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimiento.Funcionarios')),
            ],
        ),
    ]
